# Generated by Django 6.1 on 2026-08-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(default='Kerala', max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.PositiveIntegerField(help_text='District population')),
                ('literacy_rate', models.FloatField(help_text='Percent, 0-100')),
                ('police_strength', models.PositiveIntegerField(help_text='Sanctioned police personnel')),
                ('per_capita_expenditure', models.FloatField(help_text='Annual government spend per capita, INR')),
                ('forest_cover_pct', models.FloatField(help_text='Percent of district area under forest cover')),
                ('crime_rape', models.PositiveIntegerField(default=0, help_text='Reported cases / year')),
                ('crime_kidnapping', models.PositiveIntegerField(default=0, help_text='Reported cases / year')),
                ('crime_other_ipc_women', models.PositiveIntegerField(default=0, help_text='Other IPC crimes against women, reported cases / year')),
                ('crime_rate_per_100k', models.FloatField(blank=True, null=True)),
                ('police_per_100k', models.FloatField(blank=True, null=True)),
                ('literacy_disparity', models.FloatField(blank=True, help_text='Absolute gap vs. state literacy benchmark', null=True)),
                ('population_growth_rate', models.FloatField(blank=True, help_text='Percent, synthetic', null=True)),
                ('data_source', models.CharField(default='Synthetic (Open Government Data Platform format)', max_length=200)),
                ('last_ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
