# Generated by Django 6.1 on 2026-08-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('crime_rate_per_100k', models.FloatField()),
                ('police_per_100k', models.FloatField()),
                ('literacy_rate', models.FloatField()),
                ('reference_safety_score', models.FloatField(help_text='0-100, benchmark ceiling')),
            ],
            options={
                'verbose_name_plural': 'Benchmark cities',
            },
        ),
        migrations.CreateModel(
            name='SafetyCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('kmeans', 'K-Means'), ('gmm', 'Gaussian Mixture')], max_length=20)),
                ('cluster_index', models.IntegerField(help_text='Raw label id output by the model, e.g. 0-3')),
                ('tier', models.CharField(choices=[('I', 'Tier I - Benchmark Safe'), ('II', 'Tier II - Moderate'), ('III', 'Tier III - Elevated Risk'), ('IV', 'Tier IV - High Risk')], max_length=4)),
                ('color_hex', models.CharField(default='#35C4A1', max_length=7)),
                ('avg_safety_score', models.FloatField(help_text='0-100, higher = safer')),
                ('district_count', models.PositiveIntegerField(default=0)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-avg_safety_score'],
            },
        ),
        migrations.CreateModel(
            name='DistrictClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_score', models.FloatField(help_text='0-100, higher = safer')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignment', to='core.district')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='clustering.safetycluster')),
            ],
        ),
    ]
