# Generated by Django 6.1 on 2026-08-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(help_text='List of [lat, lon] points describing the planned path')),
                ('safety_buffer_km', models.FloatField(default=2.5, help_text='1.96x CI buffer radius around the route')),
                ('min_safety_score_crossed', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.district')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('safety_score_at_point', models.FloatField(blank=True, null=True)),
                ('in_unsafe_zone', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nearest_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='tracking.route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.gpsping')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.route')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
