# Generated by Django 6.1 on 2026-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='User has seen/actioned the popup for this alert.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user_response',
            field=models.CharField(blank=True, choices=[('rerouted', 'User chose: reroute me'), ('continued', "User chose: I'm okay, continue"), ('dismissed', 'User dismissed the alert')], help_text='Which popup action the user chose, if any.', max_length=20),
        ),
    ]
